baseURL = 'https://lovemjh.github.io/'

languageCode = 'zh-cn'

title = '山河故人'

theme = 'Meet'


# If true, auto-detect Chinese/Japanese/Korean Languages in the content.
# This will make .Summary and .WordCount behave correctly for CJK languages.
# 中日韩语言请改为 true
hasCJKLanguage = true # default false
isCJKLanguage = true # default false

# length of summary
# 摘要的字数限制
summaryLength = 70    # default 70
paginate = 10         # better 4 * 3 * times
enableGitInfo = true



[menus]
    [[menus.main]]
        # 名称
        name = "主页"
        # 路径
        url = "/"
        # order weight, more small more close to left, at least 1
        # 排序的权重，越小越靠前（左），最小为1
        weight = 1
        # icon from FontAwesome in front of single entry
        # 图标，本主题使用的图标来自FontAwesome
        pre = "<i class='fa fa-home'></i>"
    [[menus.main]]
        name = "文章"
        url = "/posts"
        weight = 2
        pre = "<i class='fa fa-archive'></i>"
    [[menus.main]]
        name = "归档"
        url = "/archive"
        weight = 4
        pre = "<i class='fa fa-folder-open'></i>"
    [[menus.main]]
        name = "分类"
        url = "/categories"
        weight = 4
        pre = "<i class='fa fa-folder-open'></i>"
    [[menus.main]]
        name = "标签"
        url = "/tags"
        weight = 5
        pre = "<i class='fa fa-tags'></i>"        
    [[menus.main]]
        name = "关于"
        url = "/about"
        weight = 6
        pre = "<i class='fa fa-info-circle'></i>"
  
[Params]

    #作者信息
    [Params.author]
        # 作者名称
        name = "青山"
        description = "悟已往之不谏 知来者之可追"
        # 作者头像
        # 本地路径开头”/“是必需的，亦可以链接。 下同
        # img = "/images/img.jpg"
        img = "http://q1.qlogo.cn/g?b=qq&nk=2409741052&s=640"
        # 作者卡片里 followme 和页脚作者的链接
        

    [[Params.link]]
        img = "fa fa-github"
        link = "https://github.com/xioyito"

    # 页面配置  
    [Params.page]


        # 网页背景图
        background_image_url = "/imgs/bg.jpg"

        #网页背景动画
        background_svg = "true"

        #详细定义
        # 主页的顶部图
        homeTopImg = "/images/home.jpg"
        # 主页标题
        homeTitle = "青山"
        # 主页标题字号（单位：px）
        homeTitleFontSize = 40
        # 主页打字机内容
        homeContent = "悟已往之不谏 知来者之可追"
        # 主页打字机内容字号（单位：px）
        homeContentFontSize = 20

        # 分类页面的顶部图
        categoryTopImg = "/images/categories.jpg"
        # 子标题
        categoryDes = "description of categories page"

        # 标签页面的顶部图
        tagTopImg = "/images/tag.jpg"
        # 子标题
        tagDes = "description of tags page"

        # 归档（所有文章）页面的顶部图
        allPostsTopImg = "/images/allPosts.jpg"
        # 子标题
        allPostsDes = "description of allPosts page"

        # 关于页面的顶部图
        aboutTopImg = "/images/about.jpg"
        # 子标题
        aboutDes = "description of about page"

        # 当文章没有设置图片时，将用此图来替代
        defaultPostImg = "/images/default.jpg"
        
        # 主页文章最大显示数量
        maxHomePostCount = 5
        # 相关文章最大显示数量
        maxPageRelatedCount = 5
        # 最新文章最大显示数量
        maxPageNewestCount = 5

    # Valine评论（详情请移步：https://valine.js.org/）
    [Params.valine]
        # 是否开启Valine评论系统
        enable = false
    # 页面底部配置
    [Params.footer]
        enable = true
        # copyright
        copyRight = true

# Hugo 解析文档的配置
[markup]
    # 语法高亮，详情请移步：https://gohugo.io/functions/highlight/
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        # 显示每一行代码前的序号
        lineNos = false
        anchorLineNos = false
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        # 代码高亮样式，更多样式请移步：https://xyproto.github.io/splash/docs/
        style = 'api'
        tabWidth = 4

    # 如果md文件中有html语句，请启用以下代码
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
  